installed_packages_cmd: apk -v info | awk 'BEGIN{print "Name,Version"};' | sed 's/-\([[:digit:]].*\)$/,\1/'

firewall_rules_cmd: iptables -Lv | true

services_cmd: rc-status -Cs | awk 'BEGIN{print "Name,Status"}; {print $1","$3}'

open_ports_cmd: lsof -iTCP -P -n | grep LISTEN | awk '{print $1","$3","$8","$9}'

connected_networks_cmd: ip addr | grep "inet " | awk 'BEGIN{print "Networks"}; {print $2}'

routing_table_cmd: route -n | awk 'FNR>1 {print $1","$2","$3}'

syslog_cmd: tail -n 100 /var/log/messages

