installed_packages_cmd: yum -C list installed | awk 'BEGIN{print "Name,Version"}; {if(ok==1) {print $1","$2}}; /Installed Packages/ {ok=1};' | sed 's/\...*,/,/'

firewall_rules_cmd: iptables -L -v

services_cmd: systemctl list-units --type service | awk 'BEGIN{print "Name,Status"}; NF==0 {exit}; FNR>1 {print $1","$4}'

open_ports_cmd: lsof -iTCP -P -n | grep LISTEN | awk '{print $1","$3","$8","$9}'

connected_networks_cmd: ip addr | grep "inet " | awk 'BEGIN{print "Networks"}; {print $2}'

routing_table_cmd: route -n | awk 'FNR>1 {print $1","$2","$3}'

syslog_cmd: tail -n 100 /var/log/messages

