installed_packages_cmd: rpm -qa --qf "%{NAME},%{VERSION}\n" | awk 'BEGIN{print "Name,Version"}; {print}'

firewall_rules_cmd: iptables-save

services_cmd: systemctl list-units --type service | awk 'BEGIN{print "Name,Status"}; NF==0 {exit}; FNR>1 {print $1","$4}'

open_ports_cmd: lsof -iTCP -P -n | grep LISTEN | awk '{print $1","$3","$8","$9}'

connected_networks_cmd: ip addr | grep "inet " | awk 'BEGIN{print "Networks"}; {print $2}'

routing_table_cmd: route -n | awk 'FNR>1 {print $1","$2","$3}'

syslog_cmd: journalctl -b | tail -n 100

