---
# tasks file for system-collector for debian/ubuntu hosts

- name: Creating output directory
  local_action: file path=output/{{ inventory_hostname }} state=directory
  become: no

- name: Gathering installed packages
  shell: "{{ installed_packages_cmd }}"
  register: installed_packages
- name: Saving installed packages
  local_action: copy content={{ installed_packages.stdout }} dest=output/{{ inventory_hostname }}/installed_packages.csv
  become: no
# - debug: 
#     var: installed_packages.stdout 

- name: Gathering firewall rules
  shell: "{{ firewall_rules_cmd }}"
  register: firewall_rules
- name: Saving firewall rules
  local_action: copy content={{ firewall_rules.stdout }} dest=output/{{ inventory_hostname }}/firewall_rules.txt
  become: no
# - debug: 
#     var: firewall_rules.stdout 

- name: Gathering services
  shell: "{{ services_cmd }}"
  args:
    warn: false
  register: services
- name: Saving services
  local_action: copy content={{ services.stdout }} dest=output/{{ inventory_hostname }}/services.csv
  become: no
# - debug: 
#     var: services.stdout 

- name: Ensuring lsof installed on the target system
  package:
    name: lsof
    state: present
- name: Gathering open ports
  shell: "{{ open_ports_cmd }}"
  register: open_ports
- name: Saving open ports
  local_action: copy content={{ open_ports.stdout }} dest=output/{{ inventory_hostname }}/open_ports.csv
  become: no
# - debug: 
#     var: open_ports.stdout 

- name: Gathering connected networks
  shell: "{{ connected_networks_cmd }}" 
  register: connected_networks
- name: Saving connected networks
  local_action: copy content={{ connected_networks.stdout }} dest=output/{{ inventory_hostname }}/connected_networks.csv
  become: no
# - debug: 
#     var: connected_networks.stdout 

- name: Gathering routing table
  shell: "{{ routing_table_cmd }}"
  register: routing_table
- name: Saving routing table
  local_action: copy content={{ routing_table.stdout }} dest=output/{{ inventory_hostname }}/routing_table.csv
  become: no
# - debug: 
#     var: routing_table.stdout 

- name: Gathering syslog
  shell: "{{ syslog_cmd }}"
  register: syslog 
- name: Saving syslog
  local_action: copy content={{ syslog.stdout }} dest=output/{{ inventory_hostname }}/syslog.txt
  become: no
# - debug: 
#     var: syslog.stdout 
