---
# tasks file for system-collector

- name: set os-specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - "{{ ansible_distribution | lower}}.yml"
    - "{{ ansible_os_family | lower}}.yml"
    - default.yml

- include_tasks: "{{ ansible_system | lower}}.yml"
